version: '3.1'

services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres-cl
    shm_size: '1gb'
    environment:
      POSTGRES_PASSWORD: $PG_PASS
    networks:
      - back-end

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-cl
    environment:
      - RABBITMQ_DEFAULT_USER=$RMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RMQ_PASS
    networks:
      - back-end

  redis:
    image: redis:alpine
    container_name: redis-cl
    command: redis-server --requirepass $REDIS_PASS
    networks:
      - back-end

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch-cl
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - back-end

networks:
  back-end:
