version: '3.1'

services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres-cl
    shm_size: '1gb'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: $PG_PASS
    networks:
      - back-end

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: rabbitmq-cl
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=$RMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RMQ_PASS
    networks:
      - back-end

  redis:
    image: redis:alpine
    restart: always
    container_name: redis-cl
    command: redis-server --requirepass $REDIS_PASS
    ports:
      - '6379:6379'
    networks:
      - back-end

networks:
  back-end:
